---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{.Release.Name}}
  namespace: {{.Values.namespace}}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: {{.Release.Name}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
      - name: {{.Release.Name}}
        image: {{ .Values.DockerImage }}
        imagePullPolicy: Always
        env:
          - name: DOCKER_CLEAN_INTERVAL
            value: "{{ .Values.env.dockerCleanInterval }}"
        resources:
          requests:
            cpu: {{ .Values.ressources.cpu }}
            memory: {{ .Values.ressources.memory }}
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
