---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-empty-dir-cleanup
  namespace: {{.Values.namespace}}
spec:
  schedule: "{{ .Values.schedule.etcd }}"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: etcd-empty-dir-cleanup
        spec:
          hostNetwork: true
          nodeSelector:
            kubernetes.io/role: master
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
          restartPolicy: OnFailure
          containers:
          - name: {{.Release.Name}}
            image: {{ .Values.DockerImage }}
            command: ["/bin/bash", "/bin/etcd-empty-dir-cleanup.sh"]
            resources:
              requests:
                cpu: {{ .Values.ressources.cpu }}
                memory: {{ .Values.ressources.memory }}
