---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{.Release.Name}}
  namespace: {{.Values.namespace}}
spec:
  schedule: "{{ .Values.schedule.k8s }}"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{.Release.Name}}
        spec:
          nodeSelector:
            kubernetes.io/role: master
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
          restartPolicy: OnFailure
          serviceAccountName: {{.Release.Name}}
          containers:
            - name: {{.Release.Name}}
              image: {{ .Values.DockerImage }}
              command: ["/bin/bash", "/bin/k8s-clean.sh"]
              imagePullPolicy: Always
              env:
                - name: DAYS
                  value: "{{ .Values.env.dockerCleanInterval }}"
              resources:
                requests:
                  cpu: {{ .Values.ressources.cpu }}
                  memory: {{ .Values.ressources.memory }}
